package com.chahine.tmdb.entities

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
class TvShow(
    val id: Int,
    @Json(name = "original_name") val originalName: String?,
    @Json(name = "original_language") val originalLanguage: String?,
    val overview: String?,
    val name: String?,
    @Json(name = "origin_country") val originCountry: List<String>?,
    @Json(name = "genre_ids") val genreIds: List<Int>?,
//    @Json(name = "first_air_date") val firstAirDate: LocalDate?,
    @Json(name = "backdrop_path") val backdropPath: String?,
    @Json(name = "poster_path") val posterPath: String?,
    val popularity: Double?,
    @Json(name = "vote_average") val voteAverage: Double?,
    @Json(name = "vote_count") val voteCount: Int?,
    val rating: Int?,
    @Json(name = "media_type") val mediaType: String?,
    @Json(name = "created_by") val createdBy: List<Person>?,
    val networks: List<Network>?,
    @Json(name = "episode_run_time") val episodeRunTime: List<Int>?,
    val genres: List<Genre>?,
    val homepage: String?,
    @Json(name = "in_production") val inProduction: Boolean = false,
    val languages: List<String>?,
//    @Json(name = "val") val lastAirDate: LocalDate?,
    @Json(name = "number_of_episodes") val numberOfEpisodes: Int?,
    @Json(name = "number_of_seasons") val numberOfSeasons: Int?,
    @Json(name = "production_companies") val productionCompanies: List<BaseCompany>?,
    val seasons: List<TvSeason>?,
    val status: String?,
    val type: String?,
    val images: Images?,
    val credits: Credits?,
    @Json(name = "external_ids") val externalIds: TvExternalIds?,
    @Json(name = "alternative_titles") val alternativeTitles: AlternativeTitles?,
    val changes: Changes?,
    val keywords: Keywords?,
    val recommendations: TvShowResultsPage?,
    val translations: Translations?,
    @Json(name = "content_ratings") val contentRatings: ContentRatings?,
    val similar: TvShowResultsPage?,
    val videos: Videos?,
)
