name: Feature Branch

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/src/main/java/*.kt') }}
      - name: Fetch Keystore and Properties
        run: |
          mkdir keystores
          curl -X POST https://content.dropboxapi.com/2/files/download --header "Authorization: Bearer ${{ secrets.DROPBOX_SHOWHIVE }}" --header "Dropbox-API-Arg: {\"path\": \"/debug.properties\"}" > debug.properties
          curl -X POST https://content.dropboxapi.com/2/files/download --header "Authorization: Bearer ${{ secrets.DROPBOX_SHOWHIVE }}" --header "Dropbox-API-Arg: {\"path\": \"/local.properties\"}" > local.properties
          curl -X POST https://content.dropboxapi.com/2/files/download --header "Authorization: Bearer ${{ secrets.DROPBOX_SHOWHIVE }}" --header "Dropbox-API-Arg: {\"path\": \"/keystores/debug.jks\"}" > keystores/debug.jks
      - name: Versionning
        run: |
          echo ${{ GITHUB_HEAD_REF }}
          echo "BUILD_NUMBER = $(git rev-list --count $(git rev-parse --abbrev-ref HEAD))" > version.properties
          echo "VERSION = $(git rev-parse --abbrev-ref HEAD)" >> version.properties
          echo "-->"
          cat version.properties
          echo "<--"
      - name: Static code analysis
        run: |
          ./gradlew spotlessCheck detekt
      - name: Assemble and Test Debug
        run: |
          ./gradlew :app:assembleDebug
          ./gradlew :app:testDebugUnitTest
      - name: Lint Debug
        run: |
          ./gradlew :app:lintDebug
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: showhive-lint-debug
          path: app/build/reports/
